### ISSUE TITLE
Museum - hotspotopgave, gør billedet mindre højt

### ISSUE THREAD

**Issue by jeppebundsgaard** [EJTH/open-tao-pcis#11]
Hvis vi laver billedet mindre højt, kan vi måske undgå (en del) scroll.
Altså i stedet for at det er rundt, så har vi alle kasserne på række eller i en halvcirkel omrking valgmulighederne.
![skaermbillede fra 2018-11-19 19-38-26](https://user-images.githubusercontent.com/5173690/48727555-e1771d80-ec32-11e8-90b8-0588f30e10a3.png)

**Comment by MortenTannert** [comment]
Ulf har det vist nok på sin liste over tegneopgaver at lave et mindre højt billede.

Til gengæld er det vel et problem, at svarmulighederne ligger oveni hinanden, når de bliver trukket op...?
