### ISSUE TITLE
Fejl i gantt

### ISSUE THREAD

**Issue by jeppebundsgaard** [EJTH/open-tao-pcis#12]
Den første version af gantt virkede. Men i ferniseringen får jeg følgende fejl:

gantt.js?buster=3.2.0-RC2:49 Uncaught TypeError: (d.getHours(...) + "").padStart is not a function(…)time @ gantt.js?buster=3.2.0-RC2:49tableHeader @ gantt.js?buster=3.2.0-RC2:143GanttJS @ gantt.js?buster=3.2.0-RC2:203initialize @ gantt.amd.js?buster=3.2.0-RC2:49(anonymous function) @ PortableCustomInteraction.js:191execCb @ require.js:1658check @ require.js:874enable @ require.js:1151init @ require.js:782(anonymous function) @ require.js:1424

**Comment by jeppebundsgaard** [comment]
Der er en tilsvarende fejl i en af campingpladsopgaverne.

**Comment by EJTH** [comment]
Hvilken browser og version får du denne fejl i?

**Comment by EJTH** [comment]
Jeg har tilføjet et polyfill til den manglende funktion... Det burde kun være IE og meget gamle versioner af FF og chrome denne fejl forekommer i, så det kunne være interressant at vide hvilken browser version du bruger :)
