### ISSUE TITLE
Rumdesign: Størrelse på restaurantrum

### ISSUE THREAD

**Issue by MortenTannert** [EJTH/open-tao-pcis#19]
Hej Elias
Kan du gøre restaurantrummet en smule større? Uanset hvordan man rykker rundt på figurerne, bliver det nemlig lige småt nok. En halv "bordlængde" i hver retning tror jeg er nok.

**Comment by EJTH** [comment]
Yes!

**Comment by MortenTannert** [comment]
Tak! Det fungerer fint med den nye størrelse på rummet.
