### ISSUE TITLE
brainstorm: Problem med bogstavtaster 

### ISSUE THREAD

**Issue by rusmann** [EJTH/open-tao-pcis#3]
Jeg prøvede at gennemføre en brainstormopgave som testtager og opdagede at der er en masse bogstaver på tastaturet der virker som genvejsknapper. Du kan fx ikke skrive "i" og "o" for de er zoom ud og ind, og "j" springer til næste opgave. Alle taster virker fint i de construct response-opgaver der er indbygget i tao.

**Comment by EJTH** [comment]
Det var da en sjov ting som TAO gør... altså hijacker input felter på den måde... Det havde jeg ikke lige regnet med, og jeg må indrømme at jeg mest tester i preview funktionen i TAO. Jeg har lavet en rettelse der gerne skulle virke, jeg har lagt den op sammen med de nye features, start-knap og sluttekst, som i meget gerne må indstille på opgaverne :)
