### ISSUE TITLE
Fejl i brainstorm

### ISSUE THREAD

**Issue by jeppebundsgaard** [EJTH/open-tao-pcis#8]
Jeg er i gang med at prøve brainstormen som tester.
Der sker ikke noget når jeg trykker enter. Der kommer ikkenoget frem fra de andre elever.
Jeg får følgende fejl:
Uncaught TypeError: ("" + m).padStart is not a function(…)
I brainstorm.amd.js?buster=3.2.0-RC2:24

**Comment by jeppebundsgaard** [comment]
Jeg har opdaget at hvis ikke man kan skippe, så kan man ikke komme videre - den siger at man ikke kan gå videre uden at have besvaret opgaven.
Så måske registreres det ikke korrekt at der er data (eller det løses når du har rettet den anden fejl).

**Comment by jeppebundsgaard** [comment]
Du må gerne give introteksten hvor opgaven beskrives denne class: qti-prompt

**Comment by EJTH** [comment]
Jeg har tilføjet et polyfill til padStart.

**Comment by EJTH** [comment]
Jeg er ikke helt sikker på at jeg forstår med introtekst, jeg mener ikke at det er en del af PCIen.
