### ISSUE TITLE
Fjerne brugte muligheder fra hotspot

### ISSUE THREAD

**Issue by jeppebundsgaard** [EJTH/open-tao-pcis#9]
Jeg tænker at det vil være fint om vi alle bruger denne bug-funktion - så denne bug skal måske tildeles til en af de andre (hvis den kan løses).
Når jeg trækker en valgmulighed til et hotspot (i museum hvor der skal fordeles aktiviteter på kategorier) så bliver den jeg har trukket ind, som en mulighed - kan det ændres så den forsvinder når den er brugt?

**Comment by MortenTannert** [comment]
Ja, det kan det. Man klikker bare på den valgmulighed, man vil trække op, og så angiver man "max. number of matches" til at være max 1.
Jeg har rettet det for mind map-opgaven (opg. 3) i museumsscenariet.
